"""add ai table column

Revision ID: 812b4976eb26
Revises: 11b14715966d
Create Date: 2025-08-12 15:09:52.295490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812b4976eb26'
down_revision: Union[str, Sequence[str], None] = '11b14715966d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('model_name', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ai_models_model_name'), 'ai_models', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_models_model_name'), table_name='ai_models')
    op.drop_column('ai_models', 'model_name')
    # ### end Alembic commands ###
